baseURL = "https://fanjingbo.com"
languageCode = "en-us"
title = "Fan Jingbo's Blog"
theme = "yinyang"
DefaultContentLanguage = "cn"

[languages]
  [languages.cn]
    contentDir = "content"
    languageName = "Chinese"
    weight = 2

[author]
  name = "Fanjingbo"
    homepage = "https://fanjingbo.com"


[params]
disqus = "fanjingbo-com" # disqus account name
extraHead = '<script async src="https://www.googletagmanager.com/gtag/js?id=UA-132076423-1"></script><script src="https://fanjingbo.com/analytics.js"></script>'
[[params.socials]]
name = "Github"
link = "https://github.com/flyingpot"
