name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2   
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    - name: Install coscmd
      run: |
        pip install coscmd
    - name: deploy
      run: |
        hugo --minify
        coscmd config -a ${{ secrets.SecretId }} -s ${{ secrets.SecretKey }} -b ${{ secrets.BucketName }} -r ${{ secrets.BucketRegion }} -m 10
        coscmd upload -r --delete -f public/ /
