name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout master
      uses: actions/checkout@v2
      with:
        submodules: true
    - name: hugo-cos-deploy
      uses: flyingpot/hugo-cos-deploy@1.0.4
      with:
        secret_id: ${{ secrets.SecretId }}
        secret_key: ${{ secrets.SecretKey }}
        bucket: ${{ secrets.BucketName }}
        region: ${{ secrets.BucketRegion }}
